sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '8'
cache: yarn
before_install:
  - yarn global add codecov
script:
  - yarn test -- --coverage --coverage-paths index.js
  - codecov
after_success:
  - yarn run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
